safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: bright
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Thomas Vecchione
    # url:  http://example.com/
    company:
        name: Leviathan-AVC
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
